name = "jessesdigitalventures"
client_id = ""
application_url = "https://fabulousgemsparlor.store"

[access_scopes]
scopes = "read_analytics,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_checkouts,read_customers,write_customers,read_price_rules,write_price_rules,read_discounts,write_discounts,write_inventory,read_inventory,read_metaobjects,write_metaobjects,read_orders,write_orders,read_products,write_products,read_script_tags,write_script_tags,read_shopify_payments_payouts,read_shopify_payments_bank_accounts,read_themes,write_themes"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ppd1xp-1c.myshopify.com"

[webhooks]
api_version = "2025-01"
