# This file stores configurations for your Shopify app.

client_id = "39a6bccb7e29a538d4ec8ac41dc1aa84"
name = "Fabulous Gems Dashboard"
application_url = "https://fabulousgemsparlor-store.onrender.com"

[auth]
redirect_urls = [
  "https://fabulousgemsparlor-store.onrender.com/auth/callback",
  "https://fabulousgemsparlor-store.onrender.com/auth/shopify/callback"
]

[access_scopes]
scopes = "read_orders,write_orders,read_products,read_finances"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
